Evaneos/vitaminjs

- config/index.js
Adding a field in `.vitaminrc` allowing to extend config to other files.
> extending vitaminrc files is now possible

- config/build/webpack.config.client.js
- config/defaults.js
- config/index.js
- examples/counter/package.json
- src/client/index.js
- src/server/middlewares/staticAssetsServer.js
- src/server/server.js
- src/shared/store.js
You can now add redux store enhancers (redux.enhancers)
Init function is called with store as argument (useful for adding listener / dispatch action at initialization client side)
You can now specify an object of name / path in build.client.secondaryEntries
and those files will be compiled, added to your build folder, and served by the server
[hash] works too.
> Multiple entries, store enhancers and pass store to init

- bin/vitamin.js
- config/build/webpack.config.js
- config/build/webpack.config.tests.js
- config/defaults.js
- package.json
- Adding build test bundle and mocha
Need to be done:
> Adding Test

- API.md
- bin/vitamin.es5.js
- bin/vitamin.js
- config/defaults.js
- config/index.js
- package.json
- src/client/index.js
- src/server/components/AppContainer.jsx
Some little changes, for the better :)
> Various changes

- API.md
- README.md
- config/build/webpack.config.server.js
- config/defaults.js
- src/server/components/AppContainer.jsx
- src/server/components/DivLayout.jsx
- src/server/components/HtmlLayout.jsx
- src/server/middlewares/errorHandler.jsx
- src/server/render.jsx
Now the Layout component is passed the app as a children. It only have access to head and style.
It means that you can change the layout without having to include the appcontainer which is
an internal of vitaminjs. The API is therefore more concise and more robust
> [Breaking] change Layout component api

- src/server/components/DivLayout.jsx
- src/server/components/HtmlLayout.jsx
This commit fixes a bug where the stye encoding was not correctly implemented on the server render.
> <fix> Style render in DivLayout and HtmlLayout

- config/build/webpack.config.client.js
- config/build/webpack.config.common.js
- config/build/webpack.config.server.js
- config/build/webpack.config.tests.js
- examples/counter/package.json
- examples/counter/yarn.lock
- package.json
- src/server/middlewares/errorHandler.jsx
- src/server/render.jsx
- src/server/server.js
- yarn.lock
BREAKING CHANGE:
In ES module (import or export exists in module):
-  exports is undefined
-  define is undefined
-  module.exports is read-only and undefined
> feat: stable version of webpack

- bin/vitamin.js
- config/utils/hot.js
- config/utils/killProcess.js
Instead it reload server when a file is changed
> feat: vitamin is not closed anymore when server crash

- README.md
- bin/vitamin.js
when starting vitamin in production environment, vitamin server was never called.
with @johangirod
> fix: vitamin start with env=production

- config/build/webpack.config.client.js
- src/client/index.jsx
> fix: sourcemap support for browser

- README.md
It was about time we had a nice Readme !
> docs: updates and improve README.md

- .circleci/config.yml
try to fix : https://circleci.com/gh/Evaneos/vitaminjs/1506
related ? https://discuss.circleci.com/t/yarn-connectivity-issue/10390
> tests: sometimes yarn install fails

- config/build/webpack.config.common.js
just added `ico` file extension to `url-loader` test
> feat: allow build loader to handle ico files

- package.json
> chore(package.json): add main contributors to package.json file

- bin/vitamin.js
- config/build/webpack.config.client.js
- config/build/webpack.config.common.js
- config/build/webpack.config.server.js
- config/build/webpack.config.vendor.js
- config/utils/index.js
- src/server/components/App.jsx
- src/server/middlewares/renderer.js
- src/server/render.jsx
> Optimize buildtime

- src/server/middlewares/router.js
> fix(router): error thrown during onEnter / onChange are now catched

- package.json
- yarn.lock
https://github.com/Evaneos/vitaminjs/issues/268
> build: update babel-loader to 7.0.0

- config/build/webpack.config.common.js
https://github.com/webpack-contrib/css-loader/pull/361
> refactor: css-loader has already disabled autoprefixer

- API.md
> docs(API): improve style

- API.md
- packages/vitaminjs-build/config/defaults.js
- packages/vitaminjs-runtime/src/server/server.js
> fix(server): fix server host & port log when starting
